#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    # Write your code here
    cnt=0
    m=len(arr)
    for i in range(m-1,0,-1):
        if arr[m-1]<arr[i]:
            arr[m-1]=arr[i]
        if arr[m-1]>arr[i]:
            arr[len(arr)-1] = arr[i+1]
        print(arr)
        
        

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
